return {
	-- init.lua
	-- {
	-- WARNING: will require tailwind lsp to work
	--
	-- 	"MaximilianLloyd/tw-values.nvim",
	-- 	keys = {
	-- 		{ "<leader>sv", "<cmd>TWValues<cr>", desc = "Show tailwind CSS values" },
	-- 	},
	-- 	opts = {
	-- 		border = "rounded", -- Valid window border style,
	-- 		show_unknown_classes = true, -- Shows the unknown classes popup
	-- 		focus_preview = true, -- Sets the preview as the current window
	-- 		copy_register = "", -- The register to copy values to,
	-- 		keymaps = {
	-- 			copy = "<C-y>", -- Normal mode keymap to copy the CSS values between {}
	-- 		},
	-- 	},
	-- },
	-- {
	-- 	"nanozuki/tabby.nvim",
	-- 	event = "VimEnter",
	-- 	dependencies = "nvim-tree/nvim-web-devicons",
	-- 	keys = {},
	-- 	config = function()
	-- 		vim.o.showtabline = 2
	-- 		vim.opt.sessionoptions = "curdir,folds,globals,help,tabpages,terminal,winsize"
	-- 		local theme = {
	-- 			fill = "TabLineFill",
	-- 			-- Also you can do this: fill = { fg='#f2e9de', bg='#907aa9', style='italic' }
	-- 			head = "TabLine",
	-- 			-- current_tab = 'TabLineSel',
	-- 			current_tab = { fg = "#F8FBF6", bg = "#896a98", style = "italic" },
	-- 			tab = "TabLine",
	-- 			win = "TabLine",
	-- 			tail = "TabLine",
	-- 		}
	--
	-- 		require("tabby.tabline").set(function(line)
	-- 			return {
	-- 				{
	-- 					{ "  ", hl = theme.head },
	-- 					line.sep("", theme.head, theme.fill),
	-- 				},
	-- 				line.tabs().foreach(function(tab)
	-- 					local hl = tab.is_current() and theme.current_tab or theme.tab
	-- 					return {
	-- 						line.sep("", hl, theme.fill),
	-- 						tab.is_current() and "" or "",
	-- 						tab.number(),
	-- 						tab.name(),
	-- 						-- tab.close_btn(''), -- show a close button
	-- 						line.sep("", hl, theme.fill),
	-- 						hl = hl,
	-- 						margin = " ",
	-- 					}
	-- 				end),
	-- 				line.spacer(),
	-- 				-- shows list of windows in tab
	-- 				-- line.wins_in_tab(line.api.get_current_tab()).foreach(function(win)
	-- 				--   return {
	-- 				--     line.sep('', theme.win, theme.fill),
	-- 				--     win.is_current() and '' or '',
	-- 				--     win.buf_name(),
	-- 				--     line.sep('', theme.win, theme.fill),
	-- 				--     hl = theme.win,
	-- 				--     margin = ' ',
	-- 				--   }
	-- 				-- end),
	-- 				{
	-- 					line.sep("", theme.tail, theme.fill),
	-- 					{ "  ", hl = theme.tail },
	-- 				},
	-- 				hl = theme.fill,
	-- 			}
	-- 		end)
	-- 		vim.api.nvim_set_keymap("n", "<leader>ta", ":$tabnew<CR>", { noremap = true })
	-- 		vim.api.nvim_set_keymap("n", "<leader>tc", ":tabclose<CR>", { noremap = true })
	-- 		vim.api.nvim_set_keymap("n", "<leader>to", ":tabonly<CR>", { noremap = true })
	-- 		vim.api.nvim_set_keymap("n", "<leader>tn", ":tabn<CR>", { noremap = true })
	-- 		vim.api.nvim_set_keymap("n", "<leader>tp", ":tabp<CR>", { noremap = true })
	-- 		-- move current tab to previous position
	-- 		vim.api.nvim_set_keymap("n", "<leader>tmp", ":-tabmove<CR>", { noremap = true })
	-- 		-- move current tab to next position
	-- 		vim.api.nvim_set_keymap("n", "<leader>tmn", ":+tabmove<CR>", { noremap = true })
	-- 	end,
	-- },
	-- {
	--   "tris203/hawtkeys.nvim",
	--   dependencies = {
	--     "nvim-lua/plenary.nvim",
	--     "nvim-treesitter/nvim-treesitter",
	--   },
	--   config = {
	--     -- an empty table will work for default config
	--     --- if you use functions, or whichkey, or lazy to map keys
	--     --- then please see the API below for options
	--   },
	-- }
}
